name: Trigger Docs Update

on:
  push:
    branches:
      - 'master'
  workflow_dispatch: {}

jobs:
  trigger-docs-update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger documentation generation
        env:
          GH_TOKEN: ${{ secrets.DOCS_REPO_TOKEN }}
        run: |
          gh workflow run generate-api-docs-community-contracts.yml \
            --repo OpenZeppelin/docs \
            --field tag_name="${{ github.sha }}" \
            --field trigger_type="commit"
